# Generated by Django 4.1.7 on 2023-03-17 18:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('pubs', wagtail.blocks.StructBlock([('books', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('pubs_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('pubs_title', wagtail.blocks.CharBlock(max_length=100, required=True)), ('pubs_detail', wagtail.blocks.TextBlock(required=True))])))]))], blank=True, null=True, use_json_field=None)),
                ('logo_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
            },
            bases=('wagtailcore.page',),
        ),
    ]
