# Generated by Django 4.1.7 on 2023-03-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('whyexhibit', '0002_whyexhibit_image1_whyexhibit_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyexhibit',
            name='logo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
