# Generated by Django 4.1.7 on 2023-03-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_about_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='home_message_content',
            field=models.TextField(null=True),
        ),
    ]
