# Generated by Django 4.1.7 on 2023-03-14 12:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_about_home_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='home_message_content',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
