# Generated by Django 4.1.7 on 2023-03-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('about', '0010_alter_about_home_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='home_message_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
