# Generated by Django 4.1.7 on 2023-06-23 18:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_alter_about_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='accordion',
            field=wagtail.fields.StreamField([('Accordion', wagtail.blocks.StructBlock([('board_history_accordion', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('board_list_img', wagtail.images.blocks.ImageChooserBlock(required=True)), ('board_history_header', wagtail.blocks.CharBlock(max_length=100, required=True))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
