# Generated by Django 4.1.7 on 2023-07-26 06:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_about_accordion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='accordion',
            field=wagtail.fields.StreamField([('Board_History_Accordion', wagtail.blocks.StructBlock([('first_header', wagtail.blocks.CharBlock(max_length=100, required=True)), ('first_img', wagtail.images.blocks.ImageChooserBlock(required=True)), ('board_history_accordion', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('board_list_img', wagtail.images.blocks.ImageChooserBlock(required=True)), ('board_history_header', wagtail.blocks.CharBlock(max_length=100, required=True))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
