# Generated by Django 4.1.7 on 2023-03-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_options_homepage_banner_cta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_image',
            new_name='logo_image',
        ),
    ]
