# Generated by Django 4.1.7 on 2023-03-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_carousal1_homepage_carousal2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousal_text1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousal_text2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousal_text3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
