# Generated by Django 4.1.7 on 2023-03-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0007_homepage_carousal_text1_homepage_carousal_text2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_subtitle',
            new_name='home_message_content',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_title',
            new_name='home_message_header',
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_message_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
