# Generated by Django 4.1.7 on 2023-03-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='events',
            new_name='content',
        ),
    ]
