# Generated by Django 4.1.7 on 2023-06-05 06:40

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_homepage_banner_cta_homepage_right_arrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='img_gallery',
            field=wagtail.fields.StreamField([('imgs', wagtail.blocks.StructBlock([('first_img', wagtail.images.blocks.ImageChooserBlock(required=True)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('img', wagtail.images.blocks.ImageChooserBlock(required=True)), ('img_desc', wagtail.blocks.CharBlock(max_length=100, required=True))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
