# Generated by Django 4.1.7 on 2023-07-26 10:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_homepage_img_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('imgs', wagtail.blocks.StructBlock([('first_img', wagtail.images.blocks.ImageChooserBlock(required=True)), ('first_img_desc', wagtail.blocks.CharBlock(max_length=100, required=True)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('img', wagtail.images.blocks.ImageChooserBlock(required=True)), ('img_desc', wagtail.blocks.CharBlock(max_length=100, required=True))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
